#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Florismart.Gozer.Droid.Resource", IsApplication=false)]

namespace Florismart.Gozer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int font = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int keyName = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int bold = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int bold_italic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int light = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int light_italic = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int regular = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int regular_italic = 2130903045;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Fontable = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public static int Fontable_font = 0;
			
			public static int[] Keymaster = new int[]
			{
					2130771969};
			
			// aapt resource value: 0
			public static int Keymaster_keyName = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
